name: AutomatedGeneration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git lfs install
        pip install -r requirements.txt
        git pull origin main -r
        rm -rf 9isas.csv
    - name: Scrape Data
      run: scrapy runspider spiders/SpiderLover.py -O 9isas.csv
    - name: Commit 9isas.csv
      run: |
          git config --global user.name 'sadaq'
          git config --global user.email 'sadaqabdo@protonmail.com'
          git lfs track "9isas.csv"
          git add  -f .gitattributes 9isas.csv
          git checkout 9isas.csv
          git commit -m "Automated Gen"
          git push
